package models

func AllModels() []interface{} {
	return []interface{}{
		&Account{},
		&User{},
		&Vault{},
		&Contact{},
		&UserVault{},
		&ContactVaultUser{},

		&VaultContactTemplate{},
		&VaultContactTemplatePage{},
		&VaultContactTemplateModule{},

		&Gender{},
		&Pronoun{},
		&ContactInformationType{},
		&ContactInformation{},
		&ContactImportantDateType{},
		&ContactImportantDate{},
		&ContactReminder{},
		&ContactReminderSelectedUser{},
		&ContactReminderScheduled{},
		&ContactTask{},
		&TaskContact{},
		&TaskStatus{},
		&ContactFeedItem{},

		&Emotion{},
		&CallReasonType{},
		&CallReason{},
		&Call{},
		&Note{},

		&AddressType{},
		&Address{},
		&ContactAddress{},
		&Company{},
		&ContactCompany{},

		&Currency{},
		&AccountCurrency{},
		&Loan{},
		&ContactLoan{},
		&Gift{},
		&ContactGift{},
		&GiftOccasion{},
		&GiftState{},

		&Journal{},
		&JournalMetric{},
		&PostTemplate{},
		&PostTemplateSection{},
		&Post{},
		&PostSection{},
		&PostMetric{},
		&ContactPost{},
		&Tag{},
		&PostTag{},
		&SliceOfLife{},

		&ActivityCategory{},
		&ActivityType{},
		&Activity{},
		&ActivityParticipant{},

		&PetCategory{},
		&Pet{},
		&Goal{},
		&Streak{},
		&Label{},
		&ContactLabel{},
		&QuickFact{},
		&VaultQuickFactsTemplate{},
		&Religion{},
		&File{},
		&LifeMetric{},
		&ContactLifeMetric{},
		&MoodTrackingParameter{},
		&MoodTrackingEvent{},

		&UserNotificationChannel{},
		&UserNotificationSent{},
		&UserToken{},
		&SyncToken{},
		&AddressBookSubscription{},
		&ContactSubscriptionState{},
		&DavSyncLog{},
		&Cron{},
		&Log{},

		&RelationshipGroupType{},
		&RelationshipType{},
		&Relationship{},

		&GroupType{},
		&GroupTypeRole{},
		&Group{},
		&ContactGroup{},

		&Invitation{},

		&WebAuthnCredential{},

		&OAuthProvider{},
		&GeocodingProviderConfig{},
		&SystemSetting{},
		&PersonalAccessToken{},
	}
}
