name: BuildAndPushImageOnHarbor

on:
  push:
    branches: ["simon-version"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: harbor.androz2091.fr
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v4

      - name: BuildAndPushImageOnHarbor
        run: |
          docker build ./ \
            -t harbor.androz2091.fr/personal/bonds:${SHORT_SHA} \
            -t harbor.androz2091.fr/personal/bonds:latest
          docker push harbor.androz2091.fr/personal/bonds:${SHORT_SHA}
          docker push harbor.androz2091.fr/personal/bonds:latest
